#!/usr/bin/env python

import sys
import subprocess
import json
import hashlib

def docker(args, stdin=None):
	print "# docker " + " ".join(args)
	p = subprocess.Popen(["docker"] + list(args), stdin=stdin, stdout=subprocess.PIPE)
	return p.stdout

def getId(name):
	return json.loads(docker(["inspect", name]).read())["id"]


def image_exists(img):
	return docker(["inspect", img]).read().strip() != ""

def last():
	return subprocess.Popen("docker ps -a -q | head -n 1", shell=True, stdout=subprocess.PIPE).communicate()[0].strip()

def run_and_commit(img_in, cmd, img_out, stdin=None):
	run_output = docker(["run"] + (["-i"] if stdin else []) + [img_in, "/bin/sh", "-c", "touch /tmp/$RANDOM; " + cmd], stdin=stdin)
	for line in run_output.readlines():
		print "--> " + line.rstrip()
	commit_output = docker(["commit", last(), img_out])
	return commit_output.read().rstrip()

def copy(src, dst):
	copy_job = docker(["run", "-d", src, "/bin/sh", "-c", "touch /tmp/$RANDOM"]).read().rstrip()
	docker(["wait", copy_job])
	return docker(["commit", copy_job, dst]).read().rstrip()

def changeHash(cmd, stdin):
	return hashlib.sha256("{}{}{}".format(len(cmd), cmd, stdin.read() if stdin != None else "")).hexdigest()
	

def main():
	dest = sys.argv[1]
	base=""
	for line in sys.stdin.readlines():
		line = line.strip()
		if line == "" or line[0] == "#":
			continue
		op, param = line.split("	", 1)
		if op == "from":
			print "FROM " + param
			base = param
			if not image_exists(base):
				raise Exception("No such image: " + base)
		elif op == "run":
			print "RUN " + param
			destpath = "_/changes/{}/{}".format(getId(base), changeHash(param, None))
			if not image_exists(destpath):
				print "Cache miss"
				result = run_and_commit(base, param, destpath)
			else:
				print "Cache hit"
				result = destpath
			base = result
			print "===> " + base
		elif op == "copy":
			src, dst = param.split("	", 1)
			print "COPY {} to {}".format(src, dst)
			stdin = file(src) if dst != "" else None
			print "stdin = " + str(stdin)
			cmd = "cat > {0}; chmod +x {0}".format(dst)
			destpath = "_/changes/{}/{}".format(getId(base), changeHash(param, stdin))
			stdin.seek(0)
			if not image_exists(destpath):
				print "Cache miss"
				result = run_and_commit(base, cmd, destpath, stdin=stdin)
			else:
				print "Cache hit"
				result = destpath
			base = result
			print "===> " + base
		else:
			print "Skipping uknown op " + op
	print copy(base, dest)

if __name__ == "__main__":
	main()
